# Copyright (C) 2026 Randy Li
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: RockPro64
#@DESCRIPTION: RockPro64 RK3399 board from Pine64

require include/rk3399.inc

MACHINE_FEATURES += "usbhost serial"

UBOOT_MACHINE = "rockpro64-rk3399_defconfig"
KERNEL_DEVICETREE = "rockchip/rk3399-rockpro64.dtb"

KBUILD_DEFCONFIG = "defconfig"
